### PR TITLE
Reduce logs overhead. Change it to a more idiomatic Go

### LINKED ISSUE #90: Reduce logs load to make it easier to debug issues
Debugging problems in the codebase can be a bit difficult because of two issues with the logs:
- We print the full SQL when a request fail and that SQL may be really long for some operations, making it difficult to find the right information. we should only print it partially.
- Some logs are printed several times in different situations. For example, if an error happens inside a query, that errors that may get printed 8 times as we print the `err` message each time we see it. We need to print these errors more selectively.

### PR DESCRIPTION
**Pull request by koletzilla**
## Summary
Closes https://github.com/ClickHouse/clickhouse-fivetran-destination/issues/90

The issue is that we repeated logs for some errors as we log it in each function where the error passes. I'm used to just print the stacktrace in Python, but as I'm learning, in Go it's more common to handle the error (do printing it would be considered handling) or just add context and return it [1].

So the idea is to get rid of situations like an error inside the `ExecStatement` function as that error may get printed 7 times as it passed from one function to another.

I have also reduced the sql size we print in the `ExecStatement` in case of error as that sql may contain up to 262144 B of size and we usually reach that size when doing deletes/updates.

[1] By Claude:
```
1. Dave Cheney -- "Let's talk about logging" (2015) https://dave.cheney.net/2015/11/05/lets-talk-about-logging

This is the most direct and widely-cited source. Dave Cheney (a core Go community figure). He frames logging as a form of handling -- so if you log AND return, you've handled the error twice. He explicitly states:

"If you choose to handle the error by logging it, by definition it's not an error any more -- you handled it. The act of logging an error handles the error, hence it is no longer appropriate to log it as an error."

2. Dave Cheney -- "Don't just check errors, handle them gracefully" (GothamGo 2016 talk + blog post) https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

This is a conference talk (also a blog post) where he elaborates on the principle with practical patterns. He recommends wrapping errors with context via fmt.Errorf and letting them bubble up to a single handling point.
```

### CODE REVIEW

File: destination/common/benchmark/bench.go [hunk 1]
```diff
@@ -14,7 +14,7 @@ func RunAndNotice(op func() error, opName string) error {
 	if err == nil {
 		log.Notice(fmt.Sprintf("%s completed in %d ms", opName, elapsed))
 	} else {
-		log.Notice(fmt.Sprintf("%s failed after %d ms: %s", opName, elapsed, err))
+		err = fmt.Errorf("%s failed after %d ms: %w", opName, elapsed, err)
```
Comment (kavirajk) [inline destination/common/benchmark/bench.go]: I'm seeing immediate `return` after `else` here. May be we can remove else block completely?

```go
if err != nil {
    return fmt.Error(...)
}
log.Notice()
```

File: destination/common/benchmark/bench.go [hunk 2]
```diff
@@ -26,7 +26,7 @@ func RunAndNoticeWithData[T any](op func() (T, error), opName string) (T, error)
...
```
Comment (kavirajk) [inline destination/common/benchmark/bench.go]: See my previous comment

**Review by kavirajk — APPROVED** [review]
LGTM. left few minor comments

File: destination/common/benchmark/bench.go (hunk 1 above)
Comment (koletzilla) [reply destination/common/benchmark/bench.go]: Looks good! Done :D

File: destination/common/benchmark/bench.go (hunk 2 above)
Comment (koletzilla) [reply destination/common/benchmark/bench.go]: Done :D
